version: "3.8"
services:
  chess-server:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public:ro
      - ./engine:/app/engine:ro
    environment:
      - NODE_ENV=production
